{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dronefleet-postgres-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: dronefleet-postgres
    part-of: dockops
spec:
  selector:
    app: dronefleet-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}
