apiVersion: v1
kind: Service
metadata:
  name: px4-sitl-gazebo-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: px4-sitl-gazebo
    part-of: dockops
spec:
  selector:
    app: px4-sitl-gazebo
  ports:
    - name: mavlink
      port: {{ .Values.mavlink.port }}
      targetPort: {{ .Values.mavlink.port }}
      protocol: UDP
  type: {{ .Values.service.type }}
